#!/bin/bash
# 输出学生考勤情

filename="./01-cnet/"
echo $filename

list=()
j=0
ls ${filename} | tr ' ' \n |  while read -r line
do
    list[$i]=$line
    j++
done

echo ${list[1]}

length=${#list[@]}
set length
echo $length

student=()
set student
for i in $(seq 0 9999)
do
    student[$i]=0
done

echo ${list[1]}

for file in "${list[@]}"
do
    tail -n +3 ${file} | awk '{print $1}' | uniq | sort | while read -r studentname
    do
        id=$(echo "$studentname" | sed 's/^cnet//')
        index=$id

        if [ "$index" -ge 0 ] -a [ "$index" -le 10000 ]
        then
            student[$index]=$((student[$index]+1))
        else
            echo "ignore"
        fi
    done
done

for i in $(seq 0 9999)
do
    if [ $i -ne 2948 ] -a [ student[$i] -gt 0 ]
    then
        echo "studentname:${studentname}  attendace: ${student[${studentname}]}"
    fi
done

echo ${studnt[2948]}




